include("test_indices.jl")
include("test_shelter_volume_metrics.jl")
include("test_juvenile_metrics.jl")
include("test_diversity_metrics.jl")
include("test_cover_metrics.jl")
include("test_scenario_metric.jl")
